meta_product_name: "Green Me Food"
meta_title: "Green Me Food - Livraison locale, bio et juste"
meta_description: "Trouvez des produits locaux, bio et de qualité autour de vous"
meta_image: "og-image.png"
twitter_account: "@green-me-food"   # required for Twitter Cards
